# Generated by Django 5.0.4 on 2024-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('opcoes', models.JSONField()),
                ('resposta_correta', models.CharField(max_length=100)),
            ],
        ),
    ]
